### ISSUE TITLE
Elm 0.19

### ISSUE THREAD

**Issue by marcosh** [fredcy/elm-parseint#2]
Hi,

I'm using your library as a dependency and I'd like to upgrade to Elm 0.19.
Do you have any plan to upgrade to 0.19?

**Comment by fredcy** [comment]
I haven't worked with Elm 0.19 yet. I'd gladly merge a PR to upgrade if someone has one.

**Comment by fredcy** [comment]
I upgraded the code and tests to work with Elm 0.19. I'm not seeing how to publish the update yet. Still looking at that.

**Comment by fredcy** [comment]
I just published version 2.0.1 which can run on Elm 0.19.

**Comment by marcosh** [comment]
great! thanks!
